# Generated by Django 6.0.3 on 2026-05-13 13:01

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.avatar_upload_to, verbose_name='аватар'),
        ),
    ]
